import { useState } from 'react'
import { ActionMenu } from '../components/ActionMenu'
import { PageTabs } from '../components/PageTabs'

const quizzes=[{id:'q1',title:'Jeunesse et formation',section:'Première partie',questions:10,level:'Découverte',status:'À commencer'},{id:'q2',title:'Vie familiale et habitudes',section:'Première partie',questions:12,level:'Intermédiaire',status:'Verrouillé'},{id:'q3',title:'Œuvre sacerdotale',section:'Deuxième partie',questions:15,level:'Approfondissement',status:'Verrouillé'}]
export function QuizWorkspacePage(){const[tab,setTab]=useState<'available'|'history'|'ranking'>('available');return <main className="workspace-page"><div className="page-title"><div><span className="eyebrow">Apprentissage</span><h1>Quiz du livre</h1></div></div><PageTabs tabs={[{id:'available',label:'À faire',count:quizzes.length},{id:'history',label:'Mes résultats',count:0},{id:'ranking',label:'Classement'}]} active={tab} onChange={setTab}/>
  {tab==='available'&&<div className="quiz-grid">{quizzes.map((quiz,index)=><article className="quiz-card" key={quiz.id}><div className="quiz-top"><span className="quiz-number">{String(index+1).padStart(2,'0')}</span><ActionMenu actions={[{label:'Voir les détails',onClick:()=>{}},{label:'Commencer',onClick:()=>{},disabled:quiz.status==='Verrouillé'}]}/></div><small>{quiz.section}</small><h2>{quiz.title}</h2><div className="quiz-meta"><span>{quiz.questions} questions</span><span>{quiz.level}</span></div><button className={quiz.status==='Verrouillé'?'secondary':'primary'} disabled={quiz.status==='Verrouillé'}>{quiz.status==='Verrouillé'?'Terminez la lecture précédente':'Commencer le quiz'}</button></article>)}</div>}
  {tab!=='available'&&<div className="empty-panel"><strong>{tab==='history'?'Aucune tentative enregistrée':'Classement indisponible'}</strong><p>{tab==='history'?'Vos scores et corrections apparaîtront ici.':'Le classement sera visible après la publication des quiz.'}</p></div>}
</main>}
