import { useMemo, useState } from 'react'
import { PageTabs } from '../components/PageTabs'

const chapters=[{id:'intro',label:'Préambule',pages:'12–18'},{id:'part1',label:'Première partie',pages:'19–104'},{id:'part2',label:'Deuxième partie',pages:'105–244'},{id:'part3',label:'Troisième partie',pages:'245–335'}]
export function ReadingWorkspacePage(){const[tab,setTab]=useState<'read'|'contents'|'notes'>('read');const[chapter,setChapter]=useState(chapters[0]);const[query,setQuery]=useState('');const matches=useMemo(()=>chapters.filter(c=>c.label.toLowerCase().includes(query.toLowerCase())),[query]);return <main className="workspace-page reader-page"><div className="page-title"><div><span className="eyebrow">Bibliothèque</span><h1>Le Prophète KADIMA Bakenge</h1></div><div className="reader-position">Page 1 sur 335</div></div>
  <PageTabs tabs={[{id:'read',label:'Lire'},{id:'contents',label:'Sommaire',count:chapters.length},{id:'notes',label:'Notes',count:0}]} active={tab} onChange={setTab}/>
  {tab==='read'&&<div className="reader-layout"><aside className="chapter-rail"><label className="compact-search"><span>⌕</span><input placeholder="Rechercher un chapitre" value={query} onChange={e=>setQuery(e.target.value)}/></label>{matches.map(c=><button key={c.id} className={chapter.id===c.id?'active':''} onClick={()=>setChapter(c)}><strong>{c.label}</strong><span>Pages {c.pages}</span></button>)}</aside><article className="reading-sheet"><header><small>{chapter.label}</small><h2>Contenu en attente de publication</h2></header><p>Le texte structuré du livre apparaîtra ici après l’import, la revue et la publication de sa première version. Le lecteur conservera la page source et la position de chaque passage.</p><div className="reader-tools"><button>☆ Ajouter aux favoris</button><button>✎ Prendre une note</button><button>▣ Surligner</button></div><footer><button disabled>← Passage précédent</button><button disabled>Passage suivant →</button></footer></article></div>}
  {tab==='contents'&&<div className="content-cards">{chapters.map((c,i)=><button key={c.id} onClick={()=>{setChapter(c);setTab('read')}}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{c.label}</strong><small>Pages {c.pages}</small></div><b>→</b></button>)}</div>}
  {tab==='notes'&&<div className="empty-panel"><strong>Aucune note personnelle</strong><p>Vos notes seront rattachées au passage et à la version du livre.</p></div>}
</main>}
